### ISSUE TITLE
DraftRetriever wheels file missing

### ISSUE THREAD

**Issue by drdsgvo** [FasterDecoding/REST#1]
But is mentioned in installation instruction:
"pip3 install DraftRetriever/wheels/draftretriever-0.1.0-cp39-cp39-manylinux_2_34_x86_64.whl"

Trying to build from source seems complicated if maturin/rust infrastructure not there yet (I failed and did not investigate further)

**Comment by zhenyuhe00** [comment]
Hi,
Sorry about the missing (due to gitignore). I've added the wheels file.

**Comment by zhenyuhe00** [comment]
Close this issue as the file added. Welcome to reopen it or open another issue.
