### ISSUE TITLE
What are the meanings of each parameter of the reader.search() function? k\choices\long

### ISSUE THREAD

**Issue by yangbohust** [FasterDecoding/REST#12]
https://github.com/FasterDecoding/REST/blob/6aed6ad5beb11849adfe671e874c239461ee8b84/DraftRetriever/src/lib.rs#L209-L215

Sorry, I am not familiar with rust. 
What are the meanings of each parameter of the reader.search() function?
I'm very much looking forward to your reply. Thanks.

**Comment by zhenyuhe00** [comment]
Hi, 
"py_substring" is the query (Type: python List) to search in the datastore.
"k" is the maximum number of returned sequences. I set it to 5000 for each thread by default for efficiency.
"choices" is the number of draft tokens.
"long" is the cut length of each return sequence.

**Comment by yangbohust** [comment]
Hi, 
I tried to use your database construction method on the [qwen-7b model](https://huggingface.co/Qwen/Qwen-7B) （
The "vocab_size" of the qwen-7b model is 151936）, and then tested it with the human-eval data set. I found that almost none of the draft tokens retrieved from the database were correct.

**Comment by zhenyuhe00** [comment]
I assume REST should apply to any LLM. Did you modify [modeling_qwen.py](https://huggingface.co/Qwen/Qwen-7B/blob/main/modeling_qwen.py) as the way done in [modeling_llama_kv.py](https://github.com/FasterDecoding/REST/blob/main/rest/model/modeling_llama_kv.py) ?

**Comment by yangbohust** [comment]
The "vocab_size" of the qwen-7b model is 151936, which exceeds the maximum value of 65536 that can be represented by 2 bytes. I have made the following modifications to the [lib.rs file](https://github.com/FasterDecoding/REST/blob/6aed6ad5beb11849adfe671e874c239461ee8b84/DraftRetriever/src/lib.rs). Please help me check whether the modifications are correct and whether there are any I missed something, thank you very much~

Original code:
https://github.com/FasterDecoding/REST/blob/6aed6ad5beb11849adfe671e874c239461ee8b84/DraftRetriever/src/lib.rs#L107-L128

Modified code:
```rust
    fn dump_data(
        &mut self,
    ) -> PyResult<()> {
        if self.buffer.is_empty() {
            return Ok(());
        }

        self.index_file.write_u32::<LittleEndian>((self.buffer.len() * 4) as u32)?;

        for &item in &self.buffer {
            self.index_file.write_u32::<LittleEndian>(item as u32)?;
        }

        let suffix_array = construct_suffix_array(&self.buffer, self.vocab_size);
        self.index_file.write_u32::<LittleEndian>((suffix_array.len() * 4) as u32)?;
        for suffix in suffix_array {
            self.index_file.write_i32::<LittleEndian>(suffix)?;
        }
        self.buffer.clear();

        Ok(())
    }
```


Original code:
https://github.com/FasterDecoding/REST/blob/6aed6ad5beb11849adfe671e874c239461ee8b84/DraftRetriever/src/lib.rs#L191-L194


Modified code:
```rust
            for i in (0..data_u8.len()).step_by(4) {
                let int = LittleEndian::read_u32(&data_u8[i..i+4]) as i32;
                data.push(int);
            }
```

**Comment by yangbohust** [comment]
When building a data set for the qwen-7b model, the following error message is reported. I wonder if it will affect the construction and retrieval results of the data set?

```bash
Token indices sequence length is longer than the specified maximum sequence length for this model (53946 > 32768). Running this sequence through the model will result in indexing errors
```

**Comment by zhenyuhe00** [comment]
> The "vocab_size" of the qwen-7b model is 151936, which exceeds the maximum value of 65536 that can be represented by 2 bytes. I have made the following modifications to the [lib.rs file](https://github.com/FasterDecoding/REST/blob/6aed6ad5beb11849adfe671e874c239461ee8b84/DraftRetriever/src/lib.rs). Please help me check whether the modifications are correct and whether there are any I missed something, thank you very much~
> 
> Original code:
> 
> https://github.com/FasterDecoding/REST/blob/6aed6ad5beb11849adfe671e874c239461ee8b84/DraftRetriever/src/lib.rs#L107-L128
> 
> Modified code:
> 
> ```rust
>     fn dump_data(
>         &mut self,
>     ) -> PyResult<()> {
>         if self.buffer.is_empty() {
>             return Ok(());
>         }
> 
>         self.index_file.write_u32::<LittleEndian>((self.buffer.len() * 4) as u32)?;
> 
>         for &item in &self.buffer {
>             self.index_file.write_u32::<LittleEndian>(item as u32)?;
>         }
> 
>         let suffix_array = construct_suffix_array(&self.buffer, self.vocab_size);
>         self.index_file.write_u32::<LittleEndian>((suffix_array.len() * 4) as u32)?;
>         for suffix in suffix_array {
>             self.index_file.write_i32::<LittleEndian>(suffix)?;
>         }
>         self.buffer.clear();
> 
>         Ok(())
>     }
> ```
> 
> Original code:
> 
> https://github.com/FasterDecoding/REST/blob/6aed6ad5beb11849adfe671e874c239461ee8b84/DraftRetriever/src/lib.rs#L191-L194
> 
> Modified code:
> 
> ```rust
>             for i in (0..data_u8.len()).step_by(4) {
>                 let int = LittleEndian::read_u32(&data_u8[i..i+4]) as i32;
>                 data.push(int);
>             }
> ```

I think the modifications are reasonable.

**Comment by zhenyuhe00** [comment]
> When building a data set for the qwen-7b model, the following error message is reported. I wonder if it will affect the construction and retrieval results of the data set?
> 
> ```shell
> Token indices sequence length is longer than the specified maximum sequence length for this model (53946 > 32768). Running this sequence through the model will result in indexing errors
> ```

I assume this message only indicates that the context length of Qwen is 32768. But running tokenization beyond 32768 should not be a problem, or maybe you can truncate the datastore like https://github.com/FasterDecoding/REST/issues/11.

If you have any further questions, please feel free to contact me.

**Comment by yangbohust** [comment]
Hello, have you paid attention to the paper LOOKAHEAD DECODING([Break the Sequential Dependency of LLM Inference Using LOOKAHEAD DECODING](https://arxiv.org/pdf/2402.02057))? LOOKAHEAD DECODING generates draft tokens through multiple rounds of jacobi iterations at fixed points, which can make full use of the historical information generated by the model, and your method is to retrieve the draft token from the database. May I ask what are the advantages and disadvantages of the REST solution and the LOOKAHEAD DECODING solution, and what scenarios are each suitable for?

I compared and tested the LOOKAHEAD DECODING and the REST on the human-eval data set, and found that the LOOKAHEAD DECODING has a better acceleration effect, which means that more draft tokens are guessed correctly.

 Thank you very much~

**Comment by zhenyuhe00** [comment]
> 1. what are the advantages and disadvantages of the REST solution and the LOOKAHEAD DECODING solution, and what scenarios are each suitable for?

REST requires an additional datastore for retrieval, whereas LOOKAHEAD DECODING does not. In scenarios where disk storage is limited, you may consider using LOOKAHEAD DECODING. Conversely, when disk storage is ample, REST may be a suitable option.

> 2. I compared and tested the LOOKAHEAD DECODING and the REST on the human-eval data set, and found that the LOOKAHEAD DECODING has a better acceleration effect, which means that more draft tokens are guessed correctly.

You may consider scaling up the size of the datastore to achieve faster speedup with REST.

> 3. Does accept_lengths_tree_average_micro mean that on average, ~1.633 tokens are generated per round of decoding ?

Yes. According to your statistics: 1\*0.642+2\*0.238+3\*0.063+4\*0.01897+5\*0.013827+6\*372/45271+7\*167/45271+8\*185/45271+9\*62/45271+10\*98/45271+11\*208/45271=1.644
