### ISSUE TITLE
Multi-GPU Processing Problem

### ISSUE THREAD

**Issue by mrlife219** [FasterDecoding/REST#27]
If I want to run this code in multi-GPU mode, is there anything that I need to modify?

It seems that if I roughly modify CUDA_VISIBLE_DEVICES, it may cause `expect all tensors to be on the same device, but found at least two devices`. Could you please give some hints about it?

**Comment by 2065037421** [comment]
@mrlife219 Hi, I own the same problem, have you solved it yet? Can you tell me how it was solved?
