### ISSUE TITLE
Cannot install the .whl

### ISSUE THREAD

**Issue by hasuoshenyun** [FasterDecoding/REST#4]
When I tried to install the .whl, the error occurs, "ERROR: draftretriever-0.1.0-cp39-cp39-manylinux_2_34_x86_64.whl is not a supported wheel on this platform."
My PC is linux 22.04 system.

**Comment by zhenyuhe00** [comment]
Hi,
I suppose it may be caused by the discrepancy of Linux version. You could try to build yourself:
1. install rust:
```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
2. install maturin:
```sh
pip3 install maturin==0.12
``` 
3. build from source:
```sh
cd DraftRetriever;
maturin build --release --strip -i python3.9; # will produce a .whl file
pip3 install [.whl];
``` 
It should take only a few minutes to finish these steps.     

If you have any further questions, please feel free to contact me.

**Comment by zhenyuhe00** [comment]
Welcome to reopen the issue or open another issue if you have any further questions.
